### ISSUE TITLE
module 'tensorflow.python.layers.layers' has no attribute 'Conv1D'

### ISSUE THREAD

**Issue by mst94** [OptMLGroup/VRP-RL#5]
Hello,

I have troubles when running your program.

I have installed tensorflow 1.2 as required, but also with newer tensor flow versions it fails.
The module has only the interface "conv1d", which expects some other parameters, so this also does not lead to a solution.

Do you have any idea?

Thanks in advance

```
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    main(args, prt)
  File "main.py", line 58, in main
    is_train=args['is_train'])
  File "/Projects/vrp/model/attention_agent.py", line 42, in __init__
    _scope=_scope+'Actor/')
  File "/Projects/vrp/shared/embeddings.py", line 28, in __init__
    self.project_emb = tf.layers.Conv1D(embedding_dim,1,
AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'Conv1D'
```

**Comment by msmurgui** [comment]
Hi! Have you been able to solve this issue?
